# Generated by Django 5.0.6 on 2024-05-27 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0008_alter_controlador_asignatura_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=200)),
                ('apellidos', models.CharField(max_length=200)),
                ('cedula_identidad', models.IntegerField(unique=True)),
                ('correo', models.EmailField(max_length=300)),
                ('contrasena', models.CharField(max_length=150)),
                ('rol', models.CharField(max_length=60)),
                ('estado', models.CharField(default='A', max_length=3)),
            ],
        ),
    ]
