# Generated by Django 5.0.7 on 2024-07-24 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0009_alumno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_curso', models.CharField(max_length=50)),
                ('estado', models.CharField(default='A', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('califaciones', models.BooleanField()),
                ('estado', models.CharField(default='A', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Materias',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_materias', models.CharField(max_length=200)),
                ('estado', models.CharField(default='A', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombres_notas', models.CharField(max_length=150)),
                ('estado', models.CharField(default='A', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Paralelo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_cursos', models.CharField(max_length=50)),
                ('estado', models.CharField(default='A', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Tareas',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('calificaciones', models.BooleanField()),
                ('estado', models.CharField(default='A', max_length=3)),
            ],
        ),
        migrations.RemoveField(
            model_name='controlador',
            name='asignatura',
        ),
        migrations.RemoveField(
            model_name='controlador',
            name='contenido',
        ),
        migrations.RemoveField(
            model_name='controlador',
            name='producto_academico',
        ),
        migrations.RemoveField(
            model_name='controlador',
            name='referencia',
        ),
        migrations.RemoveField(
            model_name='controlador',
            name='responsable',
        ),
        migrations.RemoveField(
            model_name='controlador',
            name='unidad',
        ),
        migrations.DeleteModel(
            name='Asignatura',
        ),
        migrations.DeleteModel(
            name='Contenido',
        ),
        migrations.DeleteModel(
            name='ProductoAcademico',
        ),
        migrations.DeleteModel(
            name='Referencias',
        ),
        migrations.DeleteModel(
            name='responsables',
        ),
        migrations.DeleteModel(
            name='Controlador',
        ),
        migrations.DeleteModel(
            name='unidades',
        ),
    ]
